### ISSUE TITLE
Feature request: an option to download a particular verison of kubectl proactively

### ISSUE THREAD

**Issue by ericpromislow** [flavio/kuberlr#11]
This would be useful for rancher desktop, which normally uses the k8s API. Right now it calls `kubectl cluster-info`, for the side-effect of getting kuberlr to verify the current version is present, and to download it if it isn't.

**Comment by flavio** [comment]
What about adding a `kuberlr get <version of k8s>` command?

**Comment by ericpromislow** [comment]
Yes, that would work.

**Comment by flavio** [comment]
This is now part of the v0.4.0 release
