### ISSUE TITLE
Please release a darwin-arm64 binary

### ISSUE THREAD

**Issue by jandubois** [flavio/kuberlr#16]
This is blocking the M1 version of Rancher Desktop.

**Comment by jandubois** [comment]
This probably requires switching to Go 1.16 or even 1.17

**Comment by jandubois** [comment]
Testing with our forked version shows that `kubectl` binaries for darwin-arm64 are only available for `v1.21.0` and later:

```console
$ curl https://storage.googleapis.com/kubernetes-release/release/v1.20.12/bin/darwin/arm64/kubectl.sha256
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.20.12/bin/darwin/arm64/kubectl.sha256</Details></Error>

$ curl https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/darwin/arm64/kubectl.sha256
290648c50b659397a9fb707e45281ab45b67254a4a2a948e460927b0d4bb7c65
```

So getting the `kuberlr` executable is just the first step. We need to discuss if we want to compile older versions for Rancher Desktop and make them available somehow. Even if we decide to do this, we would then also need to make the download location configurable in `kuberlr`.

**Comment by flavio** [comment]
As a first step I would return a better error message when someone is trying to download a darwin arm64 build of kubectl for kubernetes < `1.21.0`.

You can then figure out if Rancher Desktop should actually provide builds of kubectl for these environments.

Just my 2 cents

**Comment by flavio** [comment]
A more important question: do we have to update the GitHub Action in order to build kuberlr for Apple silicon? If not, should I just tag a new release so that you can have access to the binary from the usual localtion (this GH release page)?

**Comment by jandubois** [comment]
> do we have to update the GitHub Action in order to build kuberlr for Apple silicon?

No, just a new tag is enough to build, as long as the Go version supports it.

However, we are going to ship the amd64 version of kuberlr for Apple Silicon (users will need to use Rosetta) for our first release, so we are side-stepping this issue for now (we already need Rosetta for the UI parts because we don't know yet how to cross-build NPM modules with native code either).

So having a new release isn't urgent for us, and we'll figure out how to proceed after our 0.7.0 release.
