### ISSUE TITLE
add installation-level config path

### ISSUE THREAD

**Issue by gzm55** [flavio/kuberlr#78]
between `~/.kuberlr/kuberlr.conf` and system-wide kuberlr.conf, a kuberlr installation can load a config in the same directory with the `kuberlr` binary.

**Comment by flavio** [comment]
I have doubts about this issue. What is the concrete use case for that, what prevents you from adding the `kuberlr` configuration under your home folder?

**Comment by gzm55** [comment]
> I have doubts about this issue. What is the concrete use case for that, what prevents you from adding the `kuberlr` configuration under your home folder?

we need install kuberlr in to an NFS folder and called from many different hosts. With this feature, the admin can install and config kuberlr in one place.

**Comment by gzm55** [comment]
@flavio could you review the patch?

**Comment by flavio** [comment]
I'm not convinced about the approach of looking into the local directory. What if we add the ability to specify the path to the kuberlr configuration file with an environment variable?

That would allow something like that

```console
KUBERLR_CFG=kuberlr.toml kubectl get nodes
```

**Comment by gzm55** [comment]
> ```
> KUBERLR_CFG
> ```

Is KUBERLR_CFG going to override the user config? but `KUBERLR_CFG` cannot merge with the original user config.

**Comment by flavio** [comment]
I think we can still merge the contents of `KUBERLR_CFG` with the file eventually found under the user's home directory. We just have to give it (the `KUBERLR_CFG` file contents) higher precedence.

As stated by [this section of the README](https://github.com/flavio/kuberlr?tab=readme-ov-file#configuration):

> The configuration files are read in the order written above and merged together. Configuration files can override the values defined by the previous ones, or provide new ones.

Do you think that would satisfy your use case?

**Comment by gzm55** [comment]
> I think we can still merge the contents of `KUBERLR_CFG` with the file eventually found under the user's home directory. We just have to give it (the `KUBERLR_CFG` file contents) higher precedence.
> 
> As stated by [this section of the README](https://github.com/flavio/kuberlr?tab=readme-ov-file#configuration):
> 
> > The configuration files are read in the order written above and merged together. Configuration files can override the values defined by the previous ones, or provide new ones.
> 
> Do you think that would satisfy your use case?

Yes, this could be work

**Comment by gzm55** [comment]
what's the priority of the new config at `$KUBERLR_CFG`

**Comment by flavio** [comment]
I would read 

- `/usr/etc/kuberlr.conf`
- `/etc/kuberlr.conf`
- `$HOME/.kuberlr/kuberlr.conf`
- `$KUBERLR_CFG`

By being the last one, its contents would have the higher precedence

**Comment by gzm55** [comment]
@flavio #79 is updated, honor the new discussed env `$KUBERLR_CFG`
