### ISSUE TITLE
global options are not parsed by kuberlr

### ISSUE THREAD

**Issue by dirkmueller** [flavio/kuberlr#8]
Commands like

```shell
kubectl -n namespace create -f file.yaml
```

are failing if kubectl points to kuberlr. you need to write

```shell
kubectl create -n namespace -f file.yaml
```

instead. it would be good if all the global options (as visible via `kubectl options`) would be supported and forwarded.

**Comment by flavio** [comment]
This is now part of the v0.4.0 release
