### ISSUE TITLE
Need to check hashes of downloads before installing them in ~/.kuberlr/.../

### ISSUE THREAD

**Issue by ericpromislow** [flavio/kuberlr#9]
I switched to using version 1.19.10 from 1.21.x of kubernetes and the linked kubectl stopped working. When I looked at the storage directory I saw this:

```
$ ls -l ~/.kuberlr/darwin-amd64
total 368352
-rwxr-xr-x  1 ericp  staff  49577376 14 Jun 17:49 kubectl1.17.3
-rwxr-xr-x  1 ericp  staff  28015453 17 Jun 11:45 kubectl1.19.10
-rwxr-xr-x  1 ericp  staff  55831200 14 Jun 17:50 kubectl1.21.1
-rwxr-xr-x  1 ericp  staff  52540272 16 Jun 14:32 kubectl1.21.2
```

I redownloaded version 1.19.10 and got a file with this size:
```
rwxr-xr-x  1 ericp  staff  49397776 14 Apr 22:07 kubectl
```

And verified it:
echo "$( curl -sL 'https://dl.k8s.io/v1.19.10/bin/darwin/amd64/kubectl.sha256') kubectl" | sha256sum -c
```

**Comment by ericpromislow** [comment]
Working on a PR now

**Comment by flavio** [comment]
Fix being worked inside of this PR https://github.com/flavio/kuberlr/pull/10

**Comment by flavio** [comment]
Fixed starting from https://github.com/flavio/kuberlr/releases/tag/v0.3.2
